name: ansible-lint

on:
  workflow_call:
    inputs:
      requirements_file:
        default: ""
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ansible/ansible-lint@v24.10.0
        with:
          args: "-p --force-color"
          requirements_file: "${{ inputs.requirements_file }}"
