name: build-docker-image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      path:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      - name: build the docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: "${{ inputs.path }}/"
          tags: "${{ inputs.path }}:${{ inputs.tag }}"
