name: python-tests

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      requirements_file:
        required: false
        type: string
      tests_dir:
        required: true
        type: string

jobs:
  pytest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python_version }}"

      - name: install packages
        run: |
          if [[ -n "${{ inputs.requirements_file }}" ]]; then
            pip install -r "${{ inputs.requirements_file }}"
          else
            pip install poetry && poetry install --no-root
          fi

      - name: run pytest
        run: |
          if [[ -n "${{ inputs.requirements_file }}" ]]; then
            pytest ${{ inputs.tests_dir }}
          else
            poetry run pytest ${{ inputs.tests_dir }}
          fi
