name: terraform-lint-fmt

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: check the format of terraform files
        run: terraform fmt -check -recursive
