name: yamllint

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      yamllint_version:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ inputs.python_version }}"

      - name: install yamllint
        run: pip3 install yamllint==${{ inputs.yamllint_version }}

      - name: run yamllint
        run: yamllint .
